server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#    配置环境
#  profiles:
#    active: dev
##    order注册名称
#  application:
#    name: orderservice
#  cloud:
#    nacos:
#      server-addr: localhost:80 #nacos服务器地址
#      discovery:
#        cluster-name: SH #设置所在集群名称
#        namespace: ccd5224d-059b-417d-a9e2-9f5fc8e2f622 #配置环境隔离
#        ephemeral: true #是否是临时实例
##         server-addr: localhost:8848 #nacos服务器地址
#      config:
#        file-extension: yaml #配置文件格式
#        namespace: ccd5224d-059b-417d-a9e2-9f5fc8e2f62
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#    注册eureka客户端
#eureka:
#  client:
#    service-url:
#      #      eureka服务器地址
#      defaultZone: http://127.0.0.1:10086/eureka/
#      开启饥饿加载：服务上线就加载  默认为懒加载：服务器第一次被访问时加载
userservice:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule #nacos负载均衡


ribbon:
  eager-load:
    enabled: true
#    饥饿加载服务器名称
    clients: userservice
#    多个饥饿加载服务器配置
#      -userservice
#      -orderservice
feign:
  httpclient:
    enabled: true #开启httpclient支持
    max-connections: 200 #连接池最大连接数
    max-connections-per-route: 50 #每个路径最大链接数
  client:
    config:
      default: #default全局配置
        leggerLevel: BASIC #日志级别 一般不设置或BASIC 遇到bug可以设置full