server:
  port: 8000
  servlet:
    context-path: /
dubbo:
  application:
    name: dubbo-web
  registry:
    address: zookeeper://192.168.127.129:2181
  scan:
    base-packages: com.yuye.controller
  protocol:
    name: dubbo
    port: 20881
logging:
  level:
    root: debug
