server:
  port: 9000
  servlet:
    context-path: /
dubbo:
  application:
    name: dubbo-service
  registry:
    address: zookeeper://192.168.127.129:2181
  scan:
    base-packages: com.yuye.service.impl


